### ISSUE TITLE
ModuleNotFoundError: No module named 'numcodecs' when importing

### ISSUE THREAD

**Issue by zakwatts** [openclimatefix/ocf_blosc2#3]
## Describe the bug
Appears the package numecodes is not required when downloading

log:

from .ocf_blosc2 import Blosc2
import blosc2
from numcodecs.compat import ensure_contiguous_ndarray
from numcodecs.registry import register_codec
ModuleNotFoundError: No module named 'numcodecs'

## To Reproduce
Create a new conda environment with python version: Python 3.10.13
pip install xarray 
pip instal pandas 
pip install ocf_blosc2

then try to import and you get the bug

**Comment by zakwatts** [comment]
I can see it in the requirements.txt, but it wasn't downloaded when installing 


❯ pip install ocf_blosc2
Collecting ocf_blosc2
  Downloading ocf_blosc2-0.0.4-py3-none-any.whl (2.9 kB)
Requirement already satisfied: numpy in ./miniforge3/lib/python3.10/site-packages (from ocf_blosc2) (1.26.3)
Collecting blosc2 (from ocf_blosc2)
  Downloading blosc2-2.5.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.2 kB)
Collecting ndindex>=1.4 (from blosc2->ocf_blosc2)
  Downloading ndindex-1.7-py3-none-any.whl (85 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.7/85.7 kB 7.4 MB/s eta 0:00:00
Collecting msgpack (from blosc2->ocf_blosc2)
  Downloading msgpack-1.0.7-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.1 kB)
Collecting py-cpuinfo (from blosc2->ocf_blosc2)
  Downloading py_cpuinfo-9.0.0-py3-none-any.whl (22 kB)
Downloading blosc2-2.5.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.4/4.4 MB 24.4 MB/s eta 0:00:00
Downloading msgpack-1.0.7-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (530 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 530.8/530.8 kB 22.7 MB/s eta 0:00:00
Installing collected packages: py-cpuinfo, ndindex, msgpack, blosc2, ocf_blosc2
Successfully installed blosc2-2.5.1 msgpack-1.0.7 ndindex-1.7 ocf_blosc2-0.0.4 py-cpuinfo-9.0.0

**Comment by jacobbieker** [comment]
Should be fixed now, just pushed an update!
