### ISSUE TITLE
Get tests working

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf_blosc2#6]
The current tests are not working. Perhaps they are old ones and now are useful. 
We should fix them and get something working

**Comment by peterdudfield** [comment]
@JackKelly and /or @jacobbieker can you shed any light on these tests? Thanks

**Comment by JackKelly** [comment]
I'm afraid I didn't write any of this code.

Do we still use this repo?

I know blosc2 gives some minor improvements but maybe those improvements aren't worth the effort of maintaining our own codec adaptor?

**Comment by jacobbieker** [comment]
I think we still do in Satip, the encoding for the satellite data uses this, and I think the ICON archives as well. It did give a good boost in compression without slowing things down too much. I can take a look into it

**Comment by JackKelly** [comment]
Great, thank you Jacob! 

Having a quick look at the code: it looks like the tests are the old JpegXL tests. So they probably need converting to Blosc2

**Comment by peterdudfield** [comment]
Thanks @JackKelly and @JackKelly 

Yea this is still used in `satip`. This came up with the Manchester prize. 

Thanks for having a look at the tests

**Comment by jacobbieker** [comment]
The tests pass locally now. It does have to use a pre-2.0.0 version of Numpy as well, otherwise the blosc2 library breaks. But otherwise should be good to go.
